spring:
  security:
    user:
      name: test
      password: dingli
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.23.151:8066/fleet_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 60
      auto-commit: true
      pool-name: sgssb-hikari
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  boot:
    admin:
      client:
        url: http://${spring.security.user.name}:${spring.security.user.password}@172.16.23.151:15101
  rabbitmq:
    addresses: 172.16.23.154:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
      retry:
        max-attempts: 2
  quartz:
    job-store-type: memory
  mvc:
    async:
      request-timeout: 300000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@172.16.23.151:8762/eureka/, http://${spring.security.user.name}:${spring.security.user.password}@172.16.23.151:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
#支持配置
import:
    url: 172.16.23.151
    port: 8066
    user: root
    password: 123456
    datasource: fleet_test
    clientFlag: 0
async:
  pool:
    corePoolSize: 16
    maxPoolSize: 32
    keepAliveSeconds: 300
    queueCapacity: 2048
#
